spring.config.name=dev

mqtt.host=${MQTT_HOST}
mqtt.name=${MQTT_NAME}

discovery.id=admin
discovery.password=admin
discovery.ip=discovery-service
eureka.client.enabled=true


feign.dooray.url=${FEIGN_DOORAY_URL}
